export const MATCH_START = 'MATCH_START';
export const MATCH_LOADING = 'MATCH_LOADING';
export const MATCH_ERROR = 'MATCH_ERROR';
export const MATCH_END = 'MATCH_END';
export const MATCH_REGISTER_PLAY = 'MATCH_REGISTER_PLAY';
