export const GET_PLAYERS = 'GET_PLAYERS';
export const SWITCH_PLAYER = 'SWITCH_PLAYER';
export const PLAYERS_LOADING = 'PLAYERS_LOADING';
export const PLAYERS_ERROR = 'PLAYERS_ERROR';
export const PLAYERS_DEACTIVATE_PLAYER = 'PLAYERS_DEACTIVATE_PLAYER';
export const PLAYERS_ACTIVATE_PLAYER = 'PLAYERS_ACTIVATE_PLAYER';
